insert into MOCK_DATA (id, category, productname, price) values (1, 'dairy', 'yakitori skewers', 2137);
insert into MOCK_DATA (id, category, productname, price) values (2, 'grains', 'oatmeal cookies', 1139);
insert into MOCK_DATA (id, category, productname, price) values (3, 'sweets', 'mango salsa', 2006);
insert into MOCK_DATA (id, category, productname, price) values (4, 'beverages', 'garlic bread', 2710);
insert into MOCK_DATA (id, category, productname, price) values (5, 'frozen foods', 'waffle', 3802);
insert into MOCK_DATA (id, category, productname, price) values (6, 'grains', 'french fries', 4640);
insert into MOCK_DATA (id, category, productname, price) values (7, 'meat', 'french fries', 3967);
insert into MOCK_DATA (id, category, productname, price) values (8, 'condiments', 'salad', 4500);
insert into MOCK_DATA (id, category, productname, price) values (9, 'vegetables', 'lemon', 3160);
insert into MOCK_DATA (id, category, productname, price) values (10, 'fruits', 'mango salsa', 4470);
insert into MOCK_DATA (id, category, productname, price) values (11, 'sweets', 'mushroom risotto', 3212);
insert into MOCK_DATA (id, category, productname, price) values (12, 'dairy', 'ziti', 2595);
insert into MOCK_DATA (id, category, productname, price) values (13, 'fruits', 'mango', 122);
insert into MOCK_DATA (id, category, productname, price) values (14, 'dairy', 'sushi', 4807);
insert into MOCK_DATA (id, category, productname, price) values (15, 'dairy', 'spinach quiche', 107);
insert into MOCK_DATA (id, category, productname, price) values (16, 'snacks', 'egg salad', 2484);
insert into MOCK_DATA (id, category, productname, price) values (17, 'fruits', 'yogurt', 1475);
insert into MOCK_DATA (id, category, productname, price) values (18, 'fruits', 'macaroni', 617);
insert into MOCK_DATA (id, category, productname, price) values (19, 'sweets', 'yogurt', 1898);
insert into MOCK_DATA (id, category, productname, price) values (20, 'grains', 'veggie burger', 3824);
insert into MOCK_DATA (id, category, productname, price) values (21, 'condiments', 'ziti pasta', 3344);
insert into MOCK_DATA (id, category, productname, price) values (22, 'frozen foods', 'quesadilla', 907);
insert into MOCK_DATA (id, category, productname, price) values (23, 'frozen foods', 'queso dip', 2461);
insert into MOCK_DATA (id, category, productname, price) values (24, 'vegetables', 'ravioli', 4236);
insert into MOCK_DATA (id, category, productname, price) values (25, 'meat', 'lemon', 2111);
insert into MOCK_DATA (id, category, productname, price) values (26, 'vegetables', 'quinoa', 1702);
insert into MOCK_DATA (id, category, productname, price) values (27, 'frozen foods', 'french fries', 1630);
insert into MOCK_DATA (id, category, productname, price) values (28, 'grains', 'vietnamese pho', 3634);
insert into MOCK_DATA (id, category, productname, price) values (29, 'dairy', 'quesadilla', 320);
insert into MOCK_DATA (id, category, productname, price) values (30, 'condiments', 'lobster bisque', 1412);
insert into MOCK_DATA (id, category, productname, price) values (31, 'grains', 'quesadilla grande', 2494);
insert into MOCK_DATA (id, category, productname, price) values (32, 'dairy', 'nachos supreme', 3113);
insert into MOCK_DATA (id, category, productname, price) values (33, 'beverages', 'udon', 3692);
insert into MOCK_DATA (id, category, productname, price) values (34, 'dairy', 'lasagna', 3981);
insert into MOCK_DATA (id, category, productname, price) values (35, 'grains', 'kale salad', 2117);
insert into MOCK_DATA (id, category, productname, price) values (36, 'beverages', 'zucchini', 902);
insert into MOCK_DATA (id, category, productname, price) values (37, 'fruits', 'hamburger', 2673);
insert into MOCK_DATA (id, category, productname, price) values (38, 'dairy', 'garlic bread', 2873);
insert into MOCK_DATA (id, category, productname, price) values (39, 'vegetables', 'xmas cookies', 2304);
insert into MOCK_DATA (id, category, productname, price) values (40, 'fruits', 'fajita', 4917);
insert into MOCK_DATA (id, category, productname, price) values (41, 'grains', 'xiao long bao dumplings', 185);
insert into MOCK_DATA (id, category, productname, price) values (42, 'dairy', 'banana', 4569);
insert into MOCK_DATA (id, category, productname, price) values (43, 'condiments', 'yogurt parfait', 1926);
insert into MOCK_DATA (id, category, productname, price) values (44, 'frozen foods', 'yogurt', 845);
insert into MOCK_DATA (id, category, productname, price) values (45, 'grains', 'apple', 2614);
insert into MOCK_DATA (id, category, productname, price) values (46, 'snacks', 'yogurt parfait', 295);
insert into MOCK_DATA (id, category, productname, price) values (47, 'vegetables', 'quesadilla grande', 1834);
insert into MOCK_DATA (id, category, productname, price) values (48, 'fruits', 'ramen', 597);
insert into MOCK_DATA (id, category, productname, price) values (49, 'vegetables', 'lemon', 4274);
insert into MOCK_DATA (id, category, productname, price) values (50, 'grains', 'orange', 389);
insert into MOCK_DATA (id, category, productname, price) values (51, 'grains', 'grapes', 1479);
insert into MOCK_DATA (id, category, productname, price) values (52, 'condiments', 'pepperoni pizza', 506);
insert into MOCK_DATA (id, category, productname, price) values (53, 'dairy', 'nachos supreme', 1649);
insert into MOCK_DATA (id, category, productname, price) values (54, 'vegetables', 'taco salad', 4227);
insert into MOCK_DATA (id, category, productname, price) values (55, 'snacks', 'ice cream sundae', 1147);
insert into MOCK_DATA (id, category, productname, price) values (56, 'meat', 'nachos', 575);
insert into MOCK_DATA (id, category, productname, price) values (57, 'meat', 'egg salad', 1053);
insert into MOCK_DATA (id, category, productname, price) values (58, 'fruits', 'bagel', 291);
insert into MOCK_DATA (id, category, productname, price) values (59, 'vegetables', 'ziti', 1041);
insert into MOCK_DATA (id, category, productname, price) values (60, 'snacks', 'honeydew melon', 2870);
insert into MOCK_DATA (id, category, productname, price) values (61, 'sweets', 'hummus', 4206);
insert into MOCK_DATA (id, category, productname, price) values (62, 'sweets', 'doughnut holes', 1246);
insert into MOCK_DATA (id, category, productname, price) values (63, 'snacks', 'iceberg lettuce', 2737);
insert into MOCK_DATA (id, category, productname, price) values (64, 'condiments', 'macaroni', 3431);
insert into MOCK_DATA (id, category, productname, price) values (65, 'condiments', 'taco', 4446);
insert into MOCK_DATA (id, category, productname, price) values (66, 'meat', 'yakitori skewers', 2853);
insert into MOCK_DATA (id, category, productname, price) values (67, 'sweets', 'egg salad', 2897);
insert into MOCK_DATA (id, category, productname, price) values (68, 'condiments', 'ziti pasta', 4564);
insert into MOCK_DATA (id, category, productname, price) values (69, 'meat', 'chocolate cake', 978);
insert into MOCK_DATA (id, category, productname, price) values (70, 'snacks', 'pizza', 4601);
insert into MOCK_DATA (id, category, productname, price) values (71, 'frozen foods', 'lasagna', 4892);
insert into MOCK_DATA (id, category, productname, price) values (72, 'fruits', 'ramen noodles', 4210);
insert into MOCK_DATA (id, category, productname, price) values (73, 'snacks', 'xmas cookies', 4924);
insert into MOCK_DATA (id, category, productname, price) values (74, 'sweets', 'honeydew melon', 3141);
insert into MOCK_DATA (id, category, productname, price) values (75, 'frozen foods', 'gnocchi', 3218);
insert into MOCK_DATA (id, category, productname, price) values (76, 'grains', 'udon soup', 414);
insert into MOCK_DATA (id, category, productname, price) values (77, 'fruits', 'doughnut', 2982);
insert into MOCK_DATA (id, category, productname, price) values (78, 'vegetables', 'pepperoni pizza', 1381);
insert into MOCK_DATA (id, category, productname, price) values (79, 'vegetables', 'honeydew melon', 1967);
insert into MOCK_DATA (id, category, productname, price) values (80, 'dairy', 'egg', 3989);
insert into MOCK_DATA (id, category, productname, price) values (81, 'fruits', 'orange', 1449);
insert into MOCK_DATA (id, category, productname, price) values (82, 'beverages', 'sushi', 3210);
insert into MOCK_DATA (id, category, productname, price) values (83, 'dairy', 'oatmeal raisin cookies', 4811);
insert into MOCK_DATA (id, category, productname, price) values (84, 'vegetables', 'ice cream', 2103);
insert into MOCK_DATA (id, category, productname, price) values (85, 'snacks', 'honeydew melon', 3391);
insert into MOCK_DATA (id, category, productname, price) values (86, 'dairy', 'ramen noodles', 3741);
insert into MOCK_DATA (id, category, productname, price) values (87, 'beverages', 'chocolate cake', 1516);
insert into MOCK_DATA (id, category, productname, price) values (88, 'snacks', 'toast', 3584);
insert into MOCK_DATA (id, category, productname, price) values (89, 'frozen foods', 'sushi roll', 160);
insert into MOCK_DATA (id, category, productname, price) values (90, 'sweets', 'ramen noodles', 2338);
insert into MOCK_DATA (id, category, productname, price) values (91, 'vegetables', 'chicken nuggets', 3119);
insert into MOCK_DATA (id, category, productname, price) values (92, 'frozen foods', 'oatmeal cookies', 1007);
insert into MOCK_DATA (id, category, productname, price) values (93, 'frozen foods', 'dumplings', 1479);
insert into MOCK_DATA (id, category, productname, price) values (94, 'fruits', 'garlic bread', 4083);
insert into MOCK_DATA (id, category, productname, price) values (95, 'vegetables', 'udon soup', 3524);
insert into MOCK_DATA (id, category, productname, price) values (96, 'snacks', 'yakitori skewers', 310);
insert into MOCK_DATA (id, category, productname, price) values (97, 'frozen foods', 'ziti pasta', 2165);
insert into MOCK_DATA (id, category, productname, price) values (98, 'meat', 'rice', 3332);
insert into MOCK_DATA (id, category, productname, price) values (99, 'vegetables', 'garlic bread', 1948);
insert into MOCK_DATA (id, category, productname, price) values (100, 'beverages', 'xiao long bao', 1019);
